version: "3.7"

services:
  db:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=makeSUREtoREPLACEthis
    volumes:
      # allow database replication with authentication
      - ./scripts/pg_replica/pg_hba_init.sh:/docker-entrypoint-initdb.d/pg_hba_init.sh:ro
    # ensure pg_hba.conf is set
    command: /docker-entrypoint-initdb.d/pg_hba_init.sh docker-entrypoint.sh postgres
    shm_size: ${DB_SHM_SIZE:-64mb}
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  pgbouncer:
    image: edoburu/pgbouncer:1.21.0-p2
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=makeSUREtoREPLACEthis
      - DB_NAME=postgres
      - MAX_CLIENT_CONN=2000
      - DEFAULT_POOL_SIZE=2000
      - CLIENT_IDLE_TIMEOUT=3600
      - AUTH_TYPE=scram-sha-256
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - db
  redis:
    image: redis:7.2.4
    restart: unless-stopped
    deploy:
      replicas: ${REDIS_REPLICAS:-1}
  tph:
    # This is a dummy image name to allow `docker-compose` commands without
    # specifying multiple compose files when the containers are already up.
    # This is overridden in the specialized compose files.
    image: tph
    environment:
      - SECRET_KEY=makeSUREtoREPLACEthis
      - POSTGRES_HOST=pgbouncer
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=makeSUREtoREPLACEthis
      - REDIS_HOST=redis
      - ENABLE_BACKEND=true
      - SERVE_FIXTURES=false
    depends_on:
      - db
      - pgbouncer
      - redis
