.docker:
  image: docker:20.10.18
  services:
    - docker:20.10.18-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  tags:
    - docker

.docker-buildx:
  extends: .docker
  image: $CI_REGISTRY/teammate/docker-with-buildx:20.10.18-0.9.1
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create tls-environment
    - docker buildx create --use --name tph-builder tls-environment
  script:
    - >-
      docker buildx build
      --cache-from $IMAGE_TAG_BRANCH_CACHE
      --cache-from $IMAGE_TAG_MAIN_CACHE
      --cache-from $IMAGE_TAG_STAGING_CACHE
      ${BUILDX_CACHE:+--cache-to type=registry,mode=max,ref=$IMAGE_TAG_BRANCH_CACHE}
      ${BUILDX_PUSH:+--tag $IMAGE_TAG_SHA}
      ${BUILDX_PUSH:+--tag $IMAGE_TAG_BRANCH}
      ${BUILDX_PUSH:+--push}
      .
