#!/usr/bin/env python3
"""
This script prunes docker containers and images from old deployed branches.
"""
import os
import subprocess

MAX_BRANCHES = int(os.getenv("DEPLOY_MAX_BRANCHES", "10"))


def get_frontend_container_info():
    keys = [
        "Image",
        "CreatedAt",
        "Labels",
    ]

    p = subprocess.run(
        [
            "docker",
            "container",
            "ls",
            "--format",
            "\t".join("{{." + key + "}}" for key in keys),
            "--filter",
            "label=com.tph.is_test_branch",
        ],
        capture_output=True,
        text=True,
    )
    p.check_returncode()

    # parse out each item
    objs = []
    for line in p.stdout.strip().split("\n"):
        values = line.split("\t")
        assert len(keys) == len(values)
        obj = {}
        for key, value in zip(keys, values):
            obj[key] = value
        objs.append(obj)
    return objs


def prune(objs):
    if len(objs) > MAX_BRANCHES:
        # stop and remove earliest deployed branch
        obj = min(objs, key=lambda info: info["CreatedAt"])
        labels = {}
        for kv in obj["Labels"].split(","):
            if "=" in kv:
                k, v = kv.split("=", 1)
                labels[k] = v
        cwd = labels["com.docker.compose.project.working_dir"]

        # stop containers
        p = subprocess.run(["docker-compose", "down", "--volumes"], cwd=cwd)
        p.check_returncode()

    # remove all images not in use
    # allowed to fail, no need to check return code
    p = subprocess.run(["docker", "image", "prune", "-af"])


def main():
    objs = get_frontend_container_info()
    prune(objs)


if __name__ == "__main__":
    main()
