#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

docker-compose() {
  command docker-compose -f docker-compose.yml -f deploy/docker-compose.dev.yml "$@"
}

docker-compose build
mkdir -p client/node_modules
docker-compose up -d
docker-compose exec tph /app/server/manage.py migrate
#docker-compose exec tph /app/server/manage.py loaddata /app/server/fixtures/puzzles.yaml
#docker-compose exec tph /app/server/manage.py loaddata /app/server/fixtures/story.yaml
docker-compose exec tph /app/server/manage.py ensure_user_created admin --password admin --admin
docker-compose exec tph /app/server/manage.py ensure_user_created dev --password dev --prerelease
docker-compose exec tph /app/server/manage.py check
