#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

# Usage: ./scripts/load_fixtures

docker-compose exec tph /app/server/manage.py puzzle_fixtures fixtures/puzzles
