#!/usr/bin/env bash
set -e
REAL_SOURCE="$(perl -e "use Cwd 'abs_path'; print abs_path('${BASH_SOURCE}')")"
cd "$(dirname "$(dirname "${REAL_SOURCE}")")"

# Usage: ./scripts/save_fixtures

echo "Are you sure you have all existing puzzle changes? This will overwrite files in tph/fixtures/puzzles. [y/N]"
read line
if [[ $line == "y" ]]; then
    mkdir -p server/tph/fixtures/puzzles
    docker-compose exec tph /app/server/manage.py puzzle_fixtures fixtures/puzzles --save
else

    echo "Stopping"
    exit 1
fi
