# Generated by Django 4.0.7 on 2023-03-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotState',
        ),
    ]
