# Generated by Django 4.0.7 on 2023-02-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoilr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionAccessTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied', models.BooleanField(default=False)),
                ('interaction_access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spoilr_core.interactionaccess')),
            ],
        ),
    ]
