# Generated by Django 4.0.7 on 2023-02-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spoilr_email', '0001_initial'),
        ('spoilr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_request', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text_content', models.TextField(blank=True)),
                ('notify_emails', models.TextField(default='none')),
                ('status', models.CharField(choices=[('NR', 'No response'), ('ANS', 'Answered'), ('MOR', 'Request more info'), ('REF', 'Refund'), ('OBS', 'Obsolete'), ('RES', 'Resolved without response')], default='NR', max_length=3)),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spoilr_email.email')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoilr_core.puzzle')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_set', to='spoilr_hints.hint')),
                ('root_ancestor_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hint_thread_set', to='spoilr_hints.hint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoilr_core.team')),
            ],
        ),
        migrations.CreateModel(
            name='CannedHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(help_text='Order in the puzzle - use 0 for a hint at the very beginning of the puzzle, or 100 for a hint on extraction, and then do your best to extrapolate in between. Decimals are okay. For multiple subpuzzles, assign a whole number to each subpuzzle and use decimals off of that whole number for multiple hints in the subpuzzle.')),
                ('description', models.CharField(help_text='A description of when this hint should apply', max_length=1000)),
                ('keywords', models.CharField(blank=True, help_text="Comma-separated keywords to look for in hunters' hint requests before displaying this hint suggestion", max_length=100)),
                ('content', models.CharField(help_text='Canned hint to give a team (can be edited by us before giving it)', max_length=1000)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_hints', to='spoilr_core.puzzle')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('puzzle', 'description')},
            },
        ),
    ]
