name: build-registration

on:
  push:
    paths:
      - 'reg-client/**.tsx'
  workflow_dispatch:

jobs:
  build-registration:
    uses: ./.github/workflows/docker-buildx.yml
    with:
      push: 1
      cache: 1
      ENABLE_REGISTRATION_SITE: 1
    secrets: inherit
