name: build-posthunt

on:
  workflow_dispatch:

jobs:
  build-posthunt:
    uses: ./.github/workflows/docker-buildx.yml
    with:
      push: 1
      cache: 1
      ENABLE_POSTHUNT_SITE: 1
      ENABLE_REGISTRATION_SITE: 1
    secrets: inherit
