name: deploy-staging

on:
  workflow_dispatch:

concurrency: deploy-staging

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yml
    with:
      DEPLOY_USER: staging
      DEPLOY_HOST: staging.teammatehunt.com
      SERVER_ENVIRONMENT: staging
      BUILD_SITE: hunt-reg
      HUNT_HOST: staging.teammatehunt.com
      REGISTRATION_HOST: staging3.teammatehunt.com
      COPY_DRIVE_CREDS: 1
      EXTRA_ENV: |-
        # serve HTTP on 172.17.0.1:25080
        SERVER_HTTP_BIND_PREFIX=172.17.0.1:25
        GOOGLE_ANALYTICS_ID=FIXME
        CDN_HUNT_HOST=cdn.staging.teammatehunt.com
        CDN_REGISTRATION_HOST=cdn.staging3.teammatehunt.com
        WWW_REDIRECT=www.staging.teammatehunt.com, www.staging2.teammatehunt.com, www.staging3.teammatehunt.com
    secrets: inherit
